/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2012 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.m.MessageToast");jQuery.sap.require("sap.ui.core.Popup");sap.m.MessageToast={};sap.m.MessageToast._aPopups=[];sap.m.MessageToast._iOpenedPopups=0;sap.m.MessageToast._bNotBoundToOrientationChange=true;
sap.m.MessageToast._validateSettings=function(s){var m=s.my.split(" "),a=s.at.split(" "),c=sap.ui.core,D=c.Popup.Dock,M=this._getDockFormat(m),A=this._getDockFormat(a);if(typeof s.duration!=="number"){throw new Error(s.duration+' is of type '+typeof s.duration+', expected "number" for property "duration"')}if(!c.CSSSize.isValid(s.width)){throw new Error(s.width+' is not of type '+'"sap.ui.core.CSSSize" for property "width"')}if(typeof M!=="string"||!(M in D)){throw new Error(s.my+' is not of type '+'"sap.ui.core.Popup.Dock" for property "my"')}if(typeof A!=="string"||!(A in D)){throw new Error(s.at+' is not of type '+'"sap.ui.core.Popup.Dock" for property "at"')}if(typeof s.offset!=="string"){throw new Error(s.offset+' is of type '+typeof s.offset+', expected "string" for property "offset"')}};
sap.m.MessageToast._getDockFormat=function(m){var M=jQuery.map(m,function(M){return M.charAt(0).toUpperCase()+M.slice(1)});return M.join("")};
sap.m.MessageToast._handleOrientationChange=function(){var i,p,P;for(i=0;i<this._aPopups.length;i++){p=this._aPopups[i];if(p instanceof sap.ui.core.Popup){P=p._oPosition;p.setPosition(P.my,P.at,P.of,P.offset)}}};
sap.m.MessageToast.show=function(m,o){var s=this,$=jQuery,S=jQuery.extend({duration:3000,width:"15em",my:"center center",at:"center center",of:document,offset:"0 0"},{message:m}),p=new sap.ui.core.Popup(),h,P,M;if(o){$.extend(S,o)}this._validateSettings.call(this,S);M=$('<div class="sapMMT" style="width:'+S.width+'">'+$.sap.escapeHTML(S.message)+'</div>');P=this._aPopups.push(p)-1;p.setContent(M[0]);p.setPosition(S.my,S.at,S.of,S.offset);p.setAnimations(function fnMTOpen(a,d,O){O();s._iOpenedPopups++},function fnMTClose(a,d,c){setTimeout(function(){a.addClass("sapMMTClose").one("webkitTransitionEnd",function(){c()})},d)});p.setShadow(false);if(this._bNotBoundToOrientationChange){this._bNotBoundToOrientationChange=false;$(window).bind("resize.sapMMessageToast",jQuery.proxy(this._handleOrientationChange,this))}p.open();p.attachClosed(function h(){$(s._aPopups[P].getContent()).remove();s._aPopups[P].detachClosed(h);s._aPopups[P].destroy();s._aPopups[P]=null;s._iOpenedPopups--;if(s._iOpenedPopups===0){s._aPopups=[];$(window).unbind("resize.sapMMessageToast");s._bNotBoundToOrientationChange=true}});p.close(S.duration)};
