/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2012 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.m.Select");jQuery.sap.require("sap.m.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.m.Select",{metadata:{library:"sap.m",properties:{"name":{type:"string",group:"Misc",defaultValue:""},"visible":{type:"boolean",group:"Appearance",defaultValue:true},"enabled":{type:"boolean",group:"Behavior",defaultValue:true},"width":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:"auto"},"maxWidth":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:"100%"},"title":{type:"string",group:"Misc",defaultValue:""}},aggregations:{"items":{type:"sap.ui.core.Item",multiple:true,singularName:"item"}},associations:{"selectedItem":{type:"sap.ui.core.Item",multiple:false}},events:{"change":{}}}});sap.m.Select.M_EVENTS={'change':'change'};sap.m.Select.prototype._oRb=sap.ui.getCore().getLibraryResourceBundle("sap.m");sap.m.Select.prototype._sNoData=sap.m.Select.prototype._oRb.getText("SELECT_NO_DATA");sap.m.Select.prototype._bUseMobiscroll=(jQuery.os.android&&jQuery.os.fVersion===2.3);sap.m.Select.prototype._sLang=sap.ui.getCore().getConfiguration().getLanguage().split("-")[0];
sap.m.Select.prototype.init=function(){if(this._bUseMobiscroll){jQuery.sap.require("sap.m.SelectCustom");sap.m.Select.prototype.init=null}};
sap.m.Select.prototype.onBeforeRendering=function(){var i=this.getItems(),s=this.getAssociation("selectedItem");if(i.length){if(s===null){this.setAssociation("selectedItem",i[0].getId(),true)}else{if(!this._isSelectedItemAggregate(i,s)){jQuery.sap.log.warning("sap.m.Select.prototype.onBeforeRendering(): the selected item is not a valid item aggregation on "+this)}}}else{jQuery.sap.log.warning("sap.m.Select.prototype.onBeforeRendering(): the select does not contain any item on "+this)}this._unbindChange();if(this._bUseMobiscroll){this._onBeforeRenderingMobiscroll()}};
sap.m.Select.prototype._onBeforeRenderingMobiscroll=function(){if(this._$SltNative instanceof jQuery){this._$SltNative.scroller('destroy')}};
sap.m.Select.prototype.onAfterRendering=function(){this._$SltCont=this.$();this._$SltNative=this._$SltCont.children("select");this._$SltOptions=this._$SltNative.children("option");this._$SeletedItem=this._$SltOptions.filter(":selected");this._$SltText=this._$SltCont.children(".sapMSltText");if(this._$SltNative.length){this._$SltNative.bind("change.sapMSelect",jQuery.proxy(this._handleChange,this));this._$SltNative.css("font",this._$SltText.css("font"));if(this.getWidth()==="auto"){this._$SltCont.width(this._$SltNative.width()+parseFloat(this._$SltText.css("padding-right"))+parseFloat(this._$SltText.css("padding-left")))}}this._$SltNative.width("100%");this._$SltCont.addClass("sapMSltVisible");if(this._bUseMobiscroll){this._onAfterRenderingMobiscroll()}};
sap.m.Select.prototype._onAfterRenderingMobiscroll=function(){if(this._$SltNative.length){this._$SltNative.scroller({cancelText:this._oRb.getText("SELECT_CANCEL"),setText:this._oRb.getText("SELECT_ACCEPT"),headerText:false,lang:this._sLang,delay:300,disabled:!this.getEnabled(),display:'modal',mode:'scroller',preset:'select',showLabel:false,theme:'android-ics light',inputClass:'sapMSltInput'})}};
sap.m.Select.prototype.ontouchstart=function(e){e.originalEvent._sapui_handledByControl=true;this._$SltCont.addClass("sapMSltPressed");if(this._bUseMobiscroll){this._ontouchstartmobiscroll()}};
sap.m.Select.prototype._ontouchstartmobiscroll=function(){if(this._$SltNative.length){this._$SltNative.scroller('show')}};
sap.m.Select.prototype.ontouchend=function(){this._$SltCont.removeClass("sapMSltPressed")};
sap.m.Select.prototype._handleChange=function(){var n=this._$SltOptions.filter(":selected"),i=n.attr("id"),I=sap.ui.getCore().byId(i);if(this.getSelectedItem().getId()===i){return}this._$SeletedItem.removeAttr("selected");n.attr("selected","selected");this._$SeletedItem=n;this.setAssociation("selectedItem",i,true);this._$SltText.text(I.getText());this.fireChange({selectedItem:I})};
sap.m.Select.prototype._isSelectedItemAggregate=function(I,s){var i;for(i=0;i<I.length;i++){if(s===I[i].getId()){return true}}return false};
sap.m.Select.prototype._unbindChange=function(){if(this._$SltNative instanceof jQuery&&this._$SltNative.length){this._$SltNative.unbind("change.sapMSelect",this._handleChange)}};
sap.m.Select.prototype.getSelectedItem=function(){var s=this.getAssociation("selectedItem");return(s===null)?null:sap.ui.getCore().byId(s)};
sap.m.Select.prototype.removeAllItems=function(){this.setAssociation("selectedItem",null,false);return this.removeAllAggregation("items",false)};
sap.m.Select.prototype.removeItem=function(i){if(typeof i==="string"){i=sap.ui.getCore().byId(i)}if(!(i instanceof sap.ui.core.Item)){jQuery.sap.log.error('sap.m.Select.prototype.removeItem(): vItem must be a sap.ui.core.Item object or a valid item id on '+this);return}if(i.getId()===this.getAssociation("selectedItem")){this.setAssociation("selectedItem",null,false)}return this.removeAggregation("items",i,false)};
